# Generated by Django 4.1.2 on 2022-12-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_all_books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_book', models.CharField(max_length=30)),
                ('description_of_book', models.TextField()),
                ('image_of_book', models.ImageField(upload_to='')),
                ('author_of_book', models.CharField(max_length=50)),
                ('course_of_book', models.IntegerField()),
                ('short_description_of_book', models.TextField(max_length=100)),
            ],
        ),
    ]
