# Generated by Django 4.1.2 on 2022-12-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_model_all_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_notes_of_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_note', models.CharField(max_length=200)),
                ('text_note', models.TextField()),
                ('date_note', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
